/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.untdf.aerolineas.views;
import ar.edu.untdf.aerolineas.AerolineasApp;
import ar.edu.untdf.aerolineas.modelo.Aeropuerto;
import ar.edu.untdf.aerolineas.jtablemodelo.AeropuertosTableModel;
import ar.edu.untdf.aerolineas.jtablemodelo.AeropuertosTableListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.border.TitledBorder;
import java.awt.Rectangle;
import javax.swing.JLabel;
/**
 *
 * @author Matias
 */
public class Aeropuertos extends javax.swing.JInternalFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Aeropuertos
     */
    public Aeropuertos() {
		setRootPaneCheckingEnabled(false);
		setBorder(new TitledBorder(null, "", TitledBorder.LEADING, TitledBorder.TOP, null, null));
		//setSize(359,293);
		setTitle("Administracion de Aeropuertos");
		setClosable(true);
        initComponents();
        AeropuertosTableListener listener = new AeropuertosTableListener(this);
        tableAeropuertos.getSelectionModel().addListSelectionListener(listener);
        
        
    }

    public JButton getAceptar() {
        return aceptar;
    }

    public void setAceptar(JButton aceptar) {
        this.aceptar = aceptar;
    }

    public JButton getCancelar() {
        return cancelar;
    }

    public void setCancelar(JButton cancelar) {
        this.cancelar = cancelar;
    }

    public JTextField getFieldApellido() {
        return fieldCuidad;
    }

    public void setFieldApellido(JTextField fieldApellido) {
        this.fieldCuidad = fieldApellido;
    }


    public JTextField getFieldNombre() {
        return fieldCodigo;
    }

    public void setFieldNombre(JTextField fieldNombre) {
        this.fieldCodigo = fieldNombre;
    }

    public JTable getTableAeropuertos() {
        return tableAeropuertos;
    }

    public void setTableAeropuertos(JTable tableAeropuertos) {
        this.tableAeropuertos = tableAeropuertos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableAeropuertos = new javax.swing.JTable();
        fieldCodigo = new javax.swing.JTextField();
        fieldCuidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nuevo = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        tableAeropuertos.setModel(new ar.edu.untdf.aerolineas.jtablemodelo.AeropuertosTableModel());
        tableAeropuertos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableAeropuertos.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(tableAeropuertos);

        jLabel1.setText("Codigo");

        jLabel2.setText("Cuidad");

        nuevo.setText("Agregar");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        aceptar.setText("Guardar");
        aceptar.setEnabled(false);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
        
        JLabel lblPais = new JLabel();
        lblPais.setText("Pais");
        
        fieldPais = new JTextField();
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(18)
        			.addComponent(jLabel1)
        			.addGap(33)
        			.addComponent(fieldCodigo, GroupLayout.PREFERRED_SIZE, 206, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(nuevo, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(18)
        			.addComponent(jLabel2)
        			.addGap(33)
        			.addComponent(fieldCuidad, GroupLayout.PREFERRED_SIZE, 206, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(aceptar, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(18)
        			.addComponent(lblPais, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        			.addGap(33)
        			.addComponent(fieldPais, GroupLayout.PREFERRED_SIZE, 206, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(cancelar, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(10)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 393, GroupLayout.PREFERRED_SIZE))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(21)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(jLabel1))
        				.addComponent(fieldCodigo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(nuevo))
        			.addGap(6)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(5)
        					.addComponent(jLabel2))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(2)
        					.addComponent(fieldCuidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(aceptar))
        			.addGap(6)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(14)
        					.addComponent(lblPais))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(11)
        					.addComponent(fieldPais, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(cancelar))
        			.addGap(28)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 236, GroupLayout.PREFERRED_SIZE))
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
    fieldCuidad.setText("");
    fieldCodigo.setText("");
    aceptar.setEnabled(true);
    cancelar.setEnabled(true);
    
    }//GEN-LAST:event_nuevoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        Aeropuerto c=new Aeropuerto();
        c.setCodigo(fieldCodigo.getText());
        c.setCuidad(fieldCuidad.getText());
        c.setPais(fieldPais.getText());
        
        AerolineasApp.getAeropuertoC().create(c);
        tableAeropuertos.setModel(new AeropuertosTableModel());
        aceptar.setEnabled(false);
        cancelar.setEnabled(false);
        
        
    }//GEN-LAST:event_aceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField fieldCuidad;
    private javax.swing.JTextField fieldCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevo;
    private javax.swing.JTable tableAeropuertos;
    private JTextField fieldPais;
}
