/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.untdf.aerolineas.views;

import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author Matias
 */
public class Aplicacion extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * Creates new form Aplicacion
     */
    public Aplicacion() {
		getContentPane().setForeground(Color.YELLOW);
    	setTitle("Aerolineas Vakito Jonhs");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        AeropuertosMenu = new javax.swing.JMenu();
        AdAeropuertoMenuItem = new javax.swing.JMenuItem();
        AdAeropuertoMenuItem.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);

        	}
        });
        vuelosMenu = new javax.swing.JMenu();
        AdVueloMenuItem = new javax.swing.JMenuItem();
        AdVueloMenuItem.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);

        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AeropuertosMenu.setMnemonic('f');
        AeropuertosMenu.setText("Aeropuertos");

        AdAeropuertoMenuItem.setMnemonic('o');
        AdAeropuertoMenuItem.setText("Administrar");
        AeropuertosMenu.add(AdAeropuertoMenuItem);
        clientesMenu = new javax.swing.JMenu();
        AdClienteMenuItem = new javax.swing.JMenuItem();
        
                clientesMenu.setText("Clientes");
                
                        AdClienteMenuItem.setText("Administrar");
                        AdClienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMenuItem1ActionPerformed(evt);
                            }
                        });
                        clientesMenu.add(AdClienteMenuItem);
                        
                                menuBar.add(clientesMenu);

        menuBar.add(AeropuertosMenu);

        vuelosMenu.setMnemonic('e');
        vuelosMenu.setText("Vuelos");

        AdVueloMenuItem.setMnemonic('t');
        AdVueloMenuItem.setText("Administrar");
        vuelosMenu.add(AdVueloMenuItem);

        menuBar.add(vuelosMenu);

        setJMenuBar(menuBar);
        
        ticktesMenu = new JMenu("Tickets");
        menuBar.add(ticktesMenu);
        
        AdTicketMenuItem = new JMenuItem("Administrar");
        AdTicketMenuItem.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);

        	}
        });
        ticktesMenu.add(AdTicketMenuItem);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addComponent(desktopPane, GroupLayout.PREFERRED_SIZE, 935, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addComponent(desktopPane, GroupLayout.PREFERRED_SIZE, 603, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GroupLayout gl_desktopPane = new GroupLayout(desktopPane);
        gl_desktopPane.setHorizontalGroup(
        	gl_desktopPane.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 789, Short.MAX_VALUE)
        );
        gl_desktopPane.setVerticalGroup(
        	gl_desktopPane.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 435, Short.MAX_VALUE)
        );
        desktopPane.setLayout(gl_desktopPane);
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       this.addFrame(new Clientes(),"Listado de clientes");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.addFrame(new Aeropuertos(),"Listado de aeropuertos");
     }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.addFrame(new Vuelos(),"Listado de Vuelos");
     }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.addFrame(new Tickets(),"Listado de Tickets");
     }//GEN-LAST:event_jMenuItem1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
    }
    private javax.swing.JMenuItem AdVueloMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu vuelosMenu;
    private javax.swing.JMenu AeropuertosMenu;
    private javax.swing.JMenu clientesMenu;
    private javax.swing.JMenuItem AdClienteMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem AdAeropuertoMenuItem;
    private JMenu ticktesMenu;
    private JMenuItem AdTicketMenuItem;
    // End of variables declaration//GEN-END:variables

    public void addFrame(JInternalFrame panel, String title) {
        try {
            JInternalFrame[] children = desktopPane.getAllFrames();
            for (JInternalFrame f : children) {
                if (f.getTitle().equals(panel.getTitle())) {
                    f.setSelected(true);
                    return;
                }
            }
            desktopPane.add(panel);
            panel.setVisible(true);
            panel.setSelected(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }
}