/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.untdf.aerolineas.views;
import ar.edu.untdf.aerolineas.AerolineasApp;
import ar.edu.untdf.aerolineas.modelo.Cliente;
import ar.edu.untdf.aerolineas.jtablemodelo.ClienteTableModel;
import ar.edu.untdf.aerolineas.jtablemodelo.ClientesTableListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.border.TitledBorder;
import java.awt.Rectangle;
/**
 *
 * @author Matias
 */
public class Clientes extends javax.swing.JInternalFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Clientes
     */
    public Clientes() {
		setRootPaneCheckingEnabled(false);
		setBorder(new TitledBorder(null, "", TitledBorder.LEADING, TitledBorder.TOP, null, null));
		setSize(200,150);
		setTitle("Administracion de Clientes");
		setClosable(true);
        initComponents();
        ClientesTableListener listener = new ClientesTableListener(this);
        tableClientes.getSelectionModel().addListSelectionListener(listener);
        
        
    }

    public JButton getAceptar() {
        return aceptar;
    }

    public void setAceptar(JButton aceptar) {
        this.aceptar = aceptar;
    }

    public JButton getCancelar() {
        return cancelar;
    }

    public void setCancelar(JButton cancelar) {
        this.cancelar = cancelar;
    }

    public JTextField getFieldApellido() {
        return fieldVersion;
    }

    public void setFieldApellido(JTextField fieldApellido) {
        this.fieldVersion = fieldApellido;
    }


    public JTextField getFieldNombre() {
        return fieldNombre;
    }

    public void setFieldNombre(JTextField fieldNombre) {
        this.fieldNombre = fieldNombre;
    }

    public JTable getTableClientes() {
        return tableClientes;
    }

    public void setTableClientes(JTable tableClientes) {
        this.tableClientes = tableClientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        fieldNombre = new javax.swing.JTextField();
        fieldVersion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nuevo = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        tableClientes.setModel(new ar.edu.untdf.aerolineas.jtablemodelo.ClienteTableModel());
        tableClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableClientes.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(tableClientes);

        jLabel1.setText("Nombre");

        jLabel2.setText("Version");

        nuevo.setText("Agregar");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        aceptar.setText("Guardar");
        aceptar.setEnabled(false);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(jLabel1)
        					.addGap(33)
        					.addComponent(fieldNombre, GroupLayout.PREFERRED_SIZE, 206, GroupLayout.PREFERRED_SIZE)
        					.addGap(36)
        					.addComponent(nuevo, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(jLabel2)
        					.addGap(35)
        					.addComponent(fieldVersion, GroupLayout.PREFERRED_SIZE, 206, GroupLayout.PREFERRED_SIZE)
        					.addGap(36)
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(aceptar, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
        						.addComponent(cancelar)))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 393, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(21)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(12)
        					.addComponent(jLabel1))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(9)
        					.addComponent(fieldNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(nuevo))
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(14)
        					.addComponent(jLabel2))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(11)
        					.addComponent(fieldVersion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addComponent(aceptar)
        					.addGap(6)
        					.addComponent(cancelar)))
        			.addGap(18)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 236, GroupLayout.PREFERRED_SIZE)
        			.addGap(24))
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
    fieldVersion.setText("");
    fieldNombre.setText("");
    aceptar.setEnabled(true);
    cancelar.setEnabled(true);
    
    }//GEN-LAST:event_nuevoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        Cliente c=new Cliente();
        c.setName(fieldNombre.getText());
        c.setVersion((int) (Long.parseLong(fieldVersion.getText())));
        AerolineasApp.getClienteC().create(c);
        tableClientes.setModel(new ClienteTableModel());
        aceptar.setEnabled(false);
        cancelar.setEnabled(false);
        
        
    }//GEN-LAST:event_aceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField fieldVersion;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevo;
    private javax.swing.JTable tableClientes;
    // End of variables declaration//GEN-END:variables
}
