/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.untdf.aerolineas.views;

import ar.edu.untdf.aerolineas.AerolineasApp;
import ar.edu.untdf.aerolineas.modelo.Aeropuerto;
import ar.edu.untdf.aerolineas.modelo.Cliente;
import ar.edu.untdf.aerolineas.modelo.Ticket;
import ar.edu.untdf.aerolineas.modelo.Vuelo;
import ar.edu.untdf.aerolineas.controller.AeropuertoJpaController;
import ar.edu.untdf.aerolineas.controller.ClienteJpaController;
import ar.edu.untdf.aerolineas.controller.VueloJpaController;
import ar.edu.untdf.aerolineas.jtablemodelo.AeropuertoComboBoxModel;
import ar.edu.untdf.aerolineas.jtablemodelo.ClienteComboBoxModel;
import ar.edu.untdf.aerolineas.jtablemodelo.TicketsTableListener;
import ar.edu.untdf.aerolineas.jtablemodelo.TicketsTableModel;
import ar.edu.untdf.aerolineas.jtablemodelo.VueloComboBoxModel;

import javax.persistence.Persistence;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.border.TitledBorder;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import java.awt.Color;
import javax.swing.LayoutStyle.ComponentPlacement;
/**
 *
 * @author Matias
 */
public class Tickets extends javax.swing.JInternalFrame {

    
    private ClienteJpaController ex = new ClienteJpaController(Persistence.createEntityManagerFactory("aerolineas"));		
    private VueloJpaController ex1 = new VueloJpaController(Persistence.createEntityManagerFactory("aerolineas"));		

    private static final long serialVersionUID = 1L;
	/**
     * Creates new form Tickets
     */
    public Tickets() {
		setForeground(Color.GREEN);
		setRootPaneCheckingEnabled(false);
		setBorder(new TitledBorder(null, "", TitledBorder.LEADING, TitledBorder.TOP, null, null));
		setSize(458,448);
		setTitle("Administracion de Tickets");
		setClosable(true);
        initComponents();
        TicketsTableListener listener = new TicketsTableListener(this);
        tableTickets.getSelectionModel().addListSelectionListener(listener);
        
        
    }

    public JButton getAceptar() {
        return aceptar;
    }

    public void setAceptar(JButton aceptar) {
        this.aceptar = aceptar;
    }

    public JButton getCancelar() {
        return cancelar;
    }

    public void setCancelar(JButton cancelar) {
        this.cancelar = cancelar;
    }

    public JTable getTableTickets() {
        return tableTickets;
    }

    public void setTableTickets(JTable tableTickets) {
        this.tableTickets = tableTickets;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTickets = new javax.swing.JTable();
        nuevo = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        comboBoxCliente = new JComboBox<Cliente>();
        comboBoxVuelo = new JComboBox<Vuelo>();


        tableTickets.setModel(new ar.edu.untdf.aerolineas.jtablemodelo.TicketsTableModel());
        tableTickets.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableTickets.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(tableTickets);

        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        aceptar.setText("Guardar");
        aceptar.setEnabled(false);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
        
        comboBoxCliente.setModel(new ClienteComboBoxModel(ex));
        comboBoxCliente.setSelectedIndex(1);
        comboBoxVuelo.setModel(new VueloComboBoxModel(ex1));
        comboBoxVuelo.setSelectedIndex(1);

        JLabel lblOrigen = new JLabel("Cliente");
        
        JLabel lblDestino = new JLabel("Vuelo");
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(27)
        			.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lblOrigen)
        				.addComponent(lblDestino))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(comboBoxCliente, GroupLayout.PREFERRED_SIZE, 266, GroupLayout.PREFERRED_SIZE)
        				.addComponent(comboBoxVuelo, GroupLayout.PREFERRED_SIZE, 266, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(cancelar, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(nuevo, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(aceptar, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        		.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
        			.addContainerGap(22, Short.MAX_VALUE)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 422, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(30)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addComponent(nuevo)
        					.addGap(11)
        					.addComponent(aceptar))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblOrigen)
        						.addComponent(comboBoxCliente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(15)
        					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblDestino)
        						.addComponent(comboBoxVuelo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(cancelar)
        			.addGap(21)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 236, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
    aceptar.setEnabled(true);
    cancelar.setEnabled(true);
    
    }//GEN-LAST:event_nuevoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        Ticket c=new Ticket();
        c.setCliente((Cliente) comboBoxCliente.getSelectedItem());
        c.setVuelo((Vuelo) comboBoxVuelo.getSelectedItem());
        AerolineasApp.getTicketC().create(c);
        tableTickets.setModel(new TicketsTableModel());
        aceptar.setEnabled(false);
        cancelar.setEnabled(false);
        
        
    }//GEN-LAST:event_aceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevo;
    private javax.swing.JTable tableTickets;
    private javax.swing.JComboBox<Vuelo> comboBoxVuelo;
    private javax.swing.JComboBox<Cliente> comboBoxCliente;

}
